name: self hosted runner
on: workflow_dispatch
jobs:
  os-details:
    runs-on: self-hosted
    steps:
      - name: install nginx
        run: sudo apt install nginx -y
      - name: print os details
        run: cat /etc/os-release
      - name: print username
        run: whoami
