name: self hosted runner
on: workflow_dispatch
jobs:
  os-details:
    runs-on: self-hosted
    steps:
      - name: print worknig directory
        run: pwd
      - name: print os details
        run: cat /etc/os-release
      - name: print username
        run: whoami
